/**
 * @file config/offers.ts
 * @description Centralized configuration for all commercial offers. This is the single
 * source of truth for pricing, features, and funnel logic. All UI components and
 * business logic should import offer data from this file via the Offer Engine.
 */

import type { Offer } from "@/types/offer";

export const OFFERS: Offer[] = [
  // --- Main Pricing Page Offers ---
  {
    id: "starter",
    slug: "starter",
    name: "Starter",
    headline: "ReelForge Starter",
    price: 29,
    currency: "USD",
    billingType: "one-time",
    features: ["100 AI credits", "1080p HD exports", "Personal use license"],
    ctaText: "Get Starter",
    purchaseUrl: "/checkout?offer=starter",
    nextOffer: "order-bump",
    visible: true,
    active: true,
    priority: 10,
    analyticsKey: "STARTER_LTD",
  },
  {
    id: "pro",
    slug: "pro",
    name: "Pro",
    headline: "ReelForge Pro",
    price: 67,
    originalPrice: 97,
    currency: "USD",
    billingType: "one-time",
    recommended: true,
    badge: "Most Popular",
    features: [
      "500 AI credits",
      "4K Ultra HD exports",
      "Commercial license",
      "Priority rendering queue",
    ],
    ctaText: "Get Pro",
    purchaseUrl: "/checkout?offer=pro",
    nextOffer: "order-bump",
    visible: true,
    active: true,
    priority: 20,
    analyticsKey: "PRO_LTD",
  },
  {
    id: "agency",
    slug: "agency",
    name: "Agency",
    headline: "ReelForge Agency",
    price: 197,
    originalPrice: 297,
    currency: "USD",
    billingType: "one-time",
    features: [
      "2,000 AI credits",
      "4K Ultra HD exports",
      "Commercial & white-label license",
      "API Access & Team Seats",
    ],
    ctaText: "Get Agency",
    purchaseUrl: "/checkout?offer=agency",
    nextOffer: "order-bump",
    visible: true,
    active: true,
    priority: 30,
    analyticsKey: "AGENCY_LTD",
  },
  {
    id: "vip",
    slug: "vip",
    name: "VIP",
    headline: "ReelForge VIP",
    price: 19,
    currency: "USD",
    billingType: "monthly",
    badge: "Best Value",
    features: [
      "10,000 AI credits per month",
      "Everything in Agency",
      "Early access to new features",
    ],
    ctaText: "Go VIP",
    purchaseUrl: "/checkout?offer=vip",
    nextOffer: "order-bump",
    visible: true,
    active: true,
    priority: 40,
    analyticsKey: "VIP_MONTHLY",
  },

  // --- Funnel Offers (Upsells/Downsells) ---
  {
    id: "order-bump",
    slug: "order-bump-prompt-vault",
    name: "AI Prompt Vault",
    headline: "Instantly Add the AI Prompt Vault!",
    price: 17,
    currency: "USD",
    billingType: "one-time",
    features: ["500+ proven prompts", "Copy-paste into any studio"],
    ctaText: "Yes, Add to My Order!",
    purchaseUrl: "/checkout?offer=order-bump",
    visible: false,
    active: true,
    priority: 100,
    analyticsKey: "BUMP_PROMPT_VAULT",
  },
  {
    id: "oto-1",
    slug: "oto-pro-power-pack",
    name: "ReelForge PRO Power-Pack",
    headline: "Upgrade to PRO Power-Pack",
    price: 67,
    currency: "USD",
    billingType: "one-time",
    features: [],
    ctaText: "Upgrade Now",
    purchaseUrl: "/checkout?offer=oto-1",
    visible: false,
    active: true,
    priority: 200,
  },

  // --- Campaign/Promotional Offers ---
  {
    id: "black-friday-2026-pro",
    slug: "black-friday-pro",
    name: "Pro (Black Friday)",
    headline: "Black Friday: ReelForge Pro",
    price: 47,
    originalPrice: 97,
    currency: "USD",
    billingType: "one-time",
    features: ["Everything in Pro", "Exclusive bonus pack"],
    ctaText: "Get Black Friday Deal",
    purchaseUrl: "/checkout?offer=black-friday-2026-pro",
    visible: false,
    active: false, // Example of an inactive campaign
    priority: 999,
    analyticsKey: "BF2026_PRO_LTD",
  },
];