/**
 * MockGeminiService.ts
 *
 * Deterministic, network-free GeminiService for AI_MODE=development. Real
 * GeminiService.ts is not modified — this subclasses it so it is a true
 * GeminiService wherever one is expected (MovieProductionService's
 * constructor, GeminiLanguageModelProvider), with zero DI/type changes
 * anywhere else.
 *
 * generateText() is overridden here because the real GeminiService.ts
 * bypasses its own injected client for that one method and always calls
 * the live Gemini API directly (a pre-existing behavior in that file,
 * unrelated to this change and left untouched) — so overriding the
 * injected client alone would not be enough to stop real calls.
 * generateText() is also the only path StoryAnalyzer/CharacterDirector/
 * EnvironmentDirector/CameraDirector/EmotionDirector/ScenePlanner ever
 * reach Gemini through (via GeminiLanguageModelProvider in
 * MovieProductionFactory.ts), so this override is what actually stops the
 * entire director pipeline from calling the real API.
 *
 * generateStructuredJson()/countTokens() are inherited unchanged: both
 * already delegate to the injected client correctly, so the MockGeminiClient
 * below (passed to super()) already makes them network-free without an
 * override.
 *
 * Each of the six director stages shares this one generateText() but
 * expects a different JSON shape back. The response is chosen by a marker
 * string every stage's own prompt already contains (see StoryAnalyzer.ts/
 * CharacterDirector.ts/EnvironmentDirector.ts/CameraDirector.ts/
 * EmotionDirector.ts/ScenePlanner.ts's buildPrompt() methods — every marker
 * checked below is copied verbatim from there), and any already-generated
 * entity id it needs to reference (e.g. ScenePlanner needs real character/
 * environment ids) is read from the `id: "..."` lines those same prompts
 * already embed for the model to read — no coupling to any stage's
 * internal parsing code, just its documented prompt contract.
 */

import { GeminiService } from "../providers/google/GeminiService";
import type { GeminiClient, GeminiRequest, GeminiResponse } from "../providers/google/GeminiService";

class MockGeminiClient implements GeminiClient {
  async generate(request: GeminiRequest): Promise<GeminiResponse> {
    const text =
      request.responseFormat === "json"
        ? "{}"
        : "Mock Gemini response (AI_MODE=development) — no paid API call was made.";
    return {
      text,
      usage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
      finishReason: "MOCK",
    };
  }

  async countTokens(text: string): Promise<number> {
    return Math.max(1, Math.ceil(text.length / 4));
  }
}

export class MockGeminiService extends GeminiService {
  constructor() {
    super(new MockGeminiClient());
  }

  async generateText(_prompt: string): Promise<GeminiResponse> {
    return {
      text: this.mockDirectorResponse(_prompt),
      usage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
      finishReason: "MOCK",
    };
  }

  private mockDirectorResponse(prompt: string): string {
    if (prompt.includes('"scenes", an array')) return this.scenesResponse(prompt);
    if (prompt.includes('"emotionPlans", an array')) return this.emotionPlansResponse(prompt);
    if (prompt.includes('"cameraPlans", an array')) return this.cameraPlansResponse(prompt);
    if (prompt.includes('"environments", an array')) return this.environmentsResponse();
    if (prompt.includes('"characters", an array')) return this.charactersResponse();
    return this.storyResponse();
  }

  private storyResponse(): string {
    return JSON.stringify({
      title: "Developer Mode Test Movie",
      genre: ["DRAMA"],
      theme: "Verifying the AI pipeline without any paid API calls.",
      targetAudience: "Developers",
      estimatedDuration: 30,
      estimatedSceneCount: 1,
      conflict: "A developer needs to exercise the full pipeline safely.",
      endingStyle: "Resolved",
      emotionalArc: ["calm", "determined"],
      visualStyle: "Minimalist placeholder visuals",
    });
  }

  private charactersResponse(): string {
    return JSON.stringify({
      characters: [
        {
          name: "Mock Hero",
          description: "A placeholder character generated by Developer Mode.",
          emotionalBaseline: "CALM",
        },
      ],
    });
  }

  private environmentsResponse(): string {
    return JSON.stringify({
      environments: [
        {
          name: "Mock Location",
          description: "A placeholder location generated by Developer Mode.",
          location: "Nowhere in particular",
          architecture: "Generic",
          atmosphere: "Neutral",
          ambientSound: "Silence",
          timeOfDay: "NOON",
        },
      ],
    });
  }

  private cameraPlansResponse(prompt: string): string {
    const sceneCount = this.extractCount(prompt);
    const cameraPlans = Array.from({ length: sceneCount }, (_, i) => ({
      sceneNumber: i + 1,
      shot: "MEDIUM_SHOT",
      movement: "STATIC",
      angle: 0,
      lens: "50mm",
      framing: "Centered",
      lighting: "STUDIO",
      cameraHeight: "EYE_LEVEL",
      focusSubject: "The main subject of the scene",
      transitionToNext: "CUT",
      cinematicPurpose: "Establish the scene",
    }));
    return JSON.stringify({ cameraPlans });
  }

  private emotionPlansResponse(prompt: string): string {
    const sceneCount = this.extractCount(prompt);
    const characterIds = this.extractIds(prompt);
    const emotionPlans = Array.from({ length: sceneCount }, (_, i) => ({
      sceneNumber: i + 1,
      dominantEmotion: "CALM",
      intensity: 5,
      transition: "STEADY",
      audienceTarget: "A sense of calm resolution",
      pacingNotes: "Even pacing throughout",
      characterStates: characterIds.map((id) => ({ characterId: id, emotion: "CALM", intensity: 5 })),
    }));
    return JSON.stringify({ emotionPlans });
  }

  private scenesResponse(prompt: string): string {
    const sceneNumbers = this.extractSceneNumbers(prompt);
    const characterIds = this.extractIds(prompt, "char-");
    const environmentIds = this.extractIds(prompt, "env-");
    const scenes = sceneNumbers.map((n) => ({
      sceneNumber: n,
      title: `Mock Scene ${n}`,
      summary: "A placeholder scene generated by Developer Mode.",
      characterIds,
      environmentId: environmentIds[0],
      dialogue: [],
      estimatedRenderCost: 1,
      estimatedRenderTime: 1,
    }));
    return JSON.stringify({ scenes });
  }

  private extractCount(prompt: string): number {
    const match = prompt.match(/produce exactly (\d+)/);
    return match ? parseInt(match[1], 10) : 1;
  }

  private extractSceneNumbers(prompt: string): number[] {
    const match = prompt.match(/these scene numbers: ([\d,\s]+)\./);
    if (!match) return [1];
    return match[1]
      .split(",")
      .map((s) => parseInt(s.trim(), 10))
      .filter((n) => !Number.isNaN(n));
  }

  private extractIds(prompt: string, prefix?: string): string[] {
    const ids = [...prompt.matchAll(/id: "([^"]+)"/g)].map((m) => m[1]);
    return prefix ? ids.filter((id) => id.startsWith(prefix)) : ids;
  }
}