/**
 * mockData.ts
 *
 * Placeholder demo data for the Asset Manager. No endpoint exists yet that
 * lists individual generated assets, so this stands in until a real list
 * source exists — every field mirrors LibraryAsset exactly, so swapping
 * this out for a real fetch later is a drop-in data-source replacement.
 */

import type { AssetMetrics, AssetType, LibraryAsset } from './types'

const now = Date.now()
const hoursAgo = (h: number) => new Date(now - h * 60 * 60_000).toISOString()
const MB = 1024 * 1024

let counter = 0
function asset(partial: Omit<LibraryAsset, 'id'>): LibraryAsset {
  counter += 1
  return { id: `asset-${counter.toString().padStart(3, '0')}`, ...partial }
}

const THE_LAST_SIGNAL = 'b7f0c1a2-1111-4a1b-8c2d-000000000001'
const NEON_REQUIEM = 'b7f0c1a2-1111-4a1b-8c2d-000000000002'
const PAPER_MOON = 'b7f0c1a2-1111-4a1b-8c2d-000000000003'
const GLASS_CITY = 'b7f0c1a2-1111-4a1b-8c2d-000000000004'

export const MOCK_ASSETS: LibraryAsset[] = [
  asset({
    name: 'The Last Signal — Story Blueprint',
    type: 'STORY',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(2.4),
    resolution: null,
    fileSizeBytes: 14 * 1024,
    previewUrl: null,
    prompt: 'A brilliant detective discovers that the AI governing the city has been manipulating citizens’ memories.',
    provider: 'Gemini 2.5 Pro',
    generationTimeSeconds: 9,
    creditsUsed: 1,
    downloads: 2,
  }),
  asset({
    name: 'Mira Chen — Character Bible',
    type: 'CHARACTER',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: 'Mira Chen',
    sceneNumber: null,
    createdAt: hoursAgo(2.35),
    resolution: null,
    fileSizeBytes: 6 * 1024,
    previewUrl: null,
    prompt: 'A weary but sharp-eyed detective in her late 30s, synthetic-fiber trench coat, cybernetic left eye.',
    provider: 'Gemini 2.5 Pro',
    generationTimeSeconds: 6,
    creditsUsed: 1,
    downloads: 0,
  }),
  asset({
    name: 'Mira Chen — Reference Image',
    type: 'REFERENCE_IMAGE',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: 'Mira Chen',
    sceneNumber: null,
    createdAt: hoursAgo(2.3),
    resolution: '1024x1024',
    fileSizeBytes: 2.1 * MB,
    previewUrl: null,
    prompt: 'Studio reference portrait of Mira Chen, neutral lighting, neutral expression, full character sheet.',
    provider: 'Imagen 4',
    generationTimeSeconds: 14,
    creditsUsed: 2,
    downloads: 1,
  }),
  asset({
    name: 'Director Voss — Reference Image',
    type: 'REFERENCE_IMAGE',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: 'Director Voss',
    sceneNumber: null,
    createdAt: hoursAgo(2.28),
    resolution: '1024x1024',
    fileSizeBytes: 1.9 * MB,
    previewUrl: null,
    prompt: 'Studio reference portrait of Director Voss, austere corporate attire, cold expression.',
    provider: 'Imagen 4',
    generationTimeSeconds: 13,
    creditsUsed: 2,
    downloads: 0,
  }),
  asset({
    name: 'Scene 4 — Rooftop Chase',
    type: 'SCENE_IMAGE',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: null,
    sceneNumber: 4,
    createdAt: hoursAgo(2.1),
    resolution: '1080x1920',
    fileSizeBytes: 3.4 * MB,
    previewUrl: null,
    prompt: 'Neon-lit rooftop chase at night, rain-slicked tiles, city skyline in the background, wide shot.',
    provider: 'Imagen 4',
    generationTimeSeconds: 16,
    creditsUsed: 2,
    downloads: 0,
  }),
  asset({
    name: 'Scene 4 — Rooftop Chase',
    type: 'VIDEO',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: null,
    sceneNumber: 4,
    createdAt: hoursAgo(1.6),
    resolution: '1080x1920',
    fileSizeBytes: 38 * MB,
    previewUrl: 'https://res.cloudinary.com/demo/video/upload/the-last-signal-scene-4.mp4',
    prompt: 'Neon-lit rooftop chase at night, rain-slicked tiles, city skyline in the background, wide shot, 8s.',
    provider: 'Veo 3.1',
    generationTimeSeconds: 142,
    creditsUsed: 8,
    downloads: 3,
  }),
  asset({
    name: 'Mira Chen — Voiceover, Scene 4',
    type: 'VOICE',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: 'Mira Chen',
    sceneNumber: 4,
    createdAt: hoursAgo(1.9),
    resolution: null,
    fileSizeBytes: 1.2 * MB,
    previewUrl: 'https://res.cloudinary.com/demo/video/upload/the-last-signal-scene-4-voice.mp3',
    prompt: '"ECHO doesn\'t forget. It just decides what you\'re allowed to remember."',
    provider: 'ElevenLabs',
    generationTimeSeconds: 8,
    creditsUsed: 1,
    downloads: 0,
  }),
  asset({
    name: 'Main Theme — Synth Underscore',
    type: 'MUSIC',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(1.5),
    resolution: null,
    fileSizeBytes: 4.8 * MB,
    previewUrl: null,
    prompt: 'Tense synthwave underscore, slow build, city-at-night mood, 90s loopable.',
    provider: 'ElevenLabs Music',
    generationTimeSeconds: 22,
    creditsUsed: 3,
    downloads: 1,
  }),
  asset({
    name: 'The Last Signal — Subtitles (EN)',
    type: 'SUBTITLE',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(0.6),
    resolution: null,
    fileSizeBytes: 22 * 1024,
    previewUrl: null,
    prompt: null,
    provider: 'ffmpeg-worker',
    generationTimeSeconds: 4,
    creditsUsed: 0,
    downloads: 0,
  }),
  asset({
    name: 'The Last Signal — Poster',
    type: 'POSTER',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(0.5),
    resolution: '1080x1350',
    fileSizeBytes: 2.7 * MB,
    previewUrl: null,
    prompt: 'Theatrical poster: Mira Chen silhouetted against a wall of screens, city rain, teal and orange grade.',
    provider: 'Imagen 4',
    generationTimeSeconds: 17,
    creditsUsed: 2,
    downloads: 2,
  }),
  asset({
    name: 'The Last Signal — Thumbnail',
    type: 'THUMBNAIL',
    movieTitle: 'The Last Signal',
    productionId: THE_LAST_SIGNAL,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(0.48),
    resolution: '1280x720',
    fileSizeBytes: 640 * 1024,
    previewUrl: null,
    prompt: 'High-contrast thumbnail crop of the poster art, bold title-safe framing.',
    provider: 'Imagen 4',
    generationTimeSeconds: 6,
    creditsUsed: 1,
    downloads: 4,
  }),
  asset({
    name: 'Neon Requiem — Story Blueprint',
    type: 'STORY',
    movieTitle: 'Neon Requiem',
    productionId: NEON_REQUIEM,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(6.4),
    resolution: null,
    fileSizeBytes: 16 * 1024,
    previewUrl: null,
    prompt: 'A synthwave revenge story set in a rain-soaked megacity, told across one final night.',
    provider: 'Gemini 2.5 Pro',
    generationTimeSeconds: 11,
    creditsUsed: 1,
    downloads: 0,
  }),
  asset({
    name: 'Kade — Reference Image',
    type: 'REFERENCE_IMAGE',
    movieTitle: 'Neon Requiem',
    productionId: NEON_REQUIEM,
    characterName: 'Kade',
    sceneNumber: null,
    createdAt: hoursAgo(6.2),
    resolution: '1024x1024',
    fileSizeBytes: 2.3 * MB,
    previewUrl: null,
    prompt: 'Studio reference portrait of Kade, scarred jaw, chrome jacket, neon rim light.',
    provider: 'Imagen 4',
    generationTimeSeconds: 15,
    creditsUsed: 2,
    downloads: 0,
  }),
  asset({
    name: 'Scene 12 — Rain Duel',
    type: 'VIDEO',
    movieTitle: 'Neon Requiem',
    productionId: NEON_REQUIEM,
    characterName: null,
    sceneNumber: 12,
    createdAt: hoursAgo(5.3),
    resolution: '1080x1920',
    fileSizeBytes: 41 * MB,
    previewUrl: 'https://res.cloudinary.com/demo/video/upload/neon-requiem-scene-12.mp4',
    prompt: 'Slow-motion rain duel under a flickering neon sign, low angle, 8s.',
    provider: 'Veo 3.1',
    generationTimeSeconds: 138,
    creditsUsed: 8,
    downloads: 5,
  }),
  asset({
    name: 'Neon Requiem — Poster',
    type: 'POSTER',
    movieTitle: 'Neon Requiem',
    productionId: NEON_REQUIEM,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(4.9),
    resolution: '1080x1350',
    fileSizeBytes: 3.1 * MB,
    previewUrl: null,
    prompt: 'Theatrical poster: Kade backlit by a neon sign in falling rain, magenta and cyan grade.',
    provider: 'Imagen 4',
    generationTimeSeconds: 18,
    creditsUsed: 2,
    downloads: 6,
  }),
  asset({
    name: 'Paper Moon — Story Blueprint',
    type: 'STORY',
    movieTitle: 'Paper Moon',
    productionId: PAPER_MOON,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(30.4),
    resolution: null,
    fileSizeBytes: 12 * 1024,
    previewUrl: null,
    prompt: 'A quiet coming-of-age story about two siblings and a paper boat that won’t sink.',
    provider: 'Gemini 2.5 Pro',
    generationTimeSeconds: 8,
    creditsUsed: 1,
    downloads: 0,
  }),
  asset({
    name: 'Wren & Sam — Voiceover, Scene 9',
    type: 'VOICE',
    movieTitle: 'Paper Moon',
    productionId: PAPER_MOON,
    characterName: 'Wren',
    sceneNumber: 9,
    createdAt: hoursAgo(29.7),
    resolution: null,
    fileSizeBytes: 980 * 1024,
    previewUrl: 'https://res.cloudinary.com/demo/video/upload/paper-moon-scene-9-voice.mp3',
    prompt: '"It doesn\'t have to be perfect, Sam. It just has to float."',
    provider: 'ElevenLabs',
    generationTimeSeconds: 7,
    creditsUsed: 1,
    downloads: 1,
  }),
  asset({
    name: 'Paper Moon — Subtitles (EN)',
    type: 'SUBTITLE',
    movieTitle: 'Paper Moon',
    productionId: PAPER_MOON,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(29.0),
    resolution: null,
    fileSizeBytes: 18 * 1024,
    previewUrl: null,
    prompt: null,
    provider: 'ffmpeg-worker',
    generationTimeSeconds: 3,
    creditsUsed: 0,
    downloads: 0,
  }),
  asset({
    name: 'Glass City — Story Blueprint',
    type: 'STORY',
    movieTitle: 'Glass City',
    productionId: GLASS_CITY,
    characterName: null,
    sceneNumber: null,
    createdAt: hoursAgo(0.15),
    resolution: null,
    fileSizeBytes: 15 * 1024,
    previewUrl: null,
    prompt: 'A heist thriller set inside a city made entirely of glass towers, where every wall is a witness.',
    provider: 'Gemini 2.5 Pro',
    generationTimeSeconds: 10,
    creditsUsed: 1,
    downloads: 0,
  }),
  asset({
    name: 'Lena — Reference Image',
    type: 'REFERENCE_IMAGE',
    movieTitle: 'Glass City',
    productionId: GLASS_CITY,
    characterName: 'Lena',
    sceneNumber: null,
    createdAt: hoursAgo(0.12),
    resolution: '1024x1024',
    fileSizeBytes: 2.0 * MB,
    previewUrl: null,
    prompt: 'Studio reference portrait of Lena, tactical jumpsuit, reflective visor pushed up.',
    provider: 'Imagen 4',
    generationTimeSeconds: 14,
    creditsUsed: 2,
    downloads: 0,
  }),
]

function bucketForMetrics(type: AssetType): 'image' | 'video' | 'voice' | 'story' | 'other' {
  switch (type) {
    case 'REFERENCE_IMAGE':
    case 'SCENE_IMAGE':
    case 'POSTER':
    case 'THUMBNAIL':
      return 'image'
    case 'VIDEO':
      return 'video'
    case 'VOICE':
      return 'voice'
    case 'STORY':
      return 'story'
    default:
      return 'other'
  }
}

export function computeAssetMetrics(assetsList: LibraryAsset[]): AssetMetrics {
  return {
    totalAssets: assetsList.length,
    images: assetsList.filter((a) => bucketForMetrics(a.type) === 'image').length,
    videos: assetsList.filter((a) => bucketForMetrics(a.type) === 'video').length,
    voiceFiles: assetsList.filter((a) => bucketForMetrics(a.type) === 'voice').length,
    storyFiles: assetsList.filter((a) => bucketForMetrics(a.type) === 'story').length,
    storageUsedBytes: assetsList.reduce((sum, a) => sum + a.fileSizeBytes, 0),
    downloads: assetsList.reduce((sum, a) => sum + a.downloads, 0),
  }
}
