import { Film, ImageIcon, Music2, Play, Volume2, Waves } from "lucide-react";
import type { AssetInspectorData } from "@/services/infrastructure/SceneStudioFactory";

export interface AssetInspectorPanelProps {
  assets: AssetInspectorData;
}

/**
 * Module 7 — reuses AssetManager's real outputs: reference images off
 * Character/Environment (already-generated, Stage 2), the music cue from
 * MusicPlanner's real MusicPlan (via AssetCatalog.musicPlan), voice
 * assignments off Character.voiceProfile, and sound effects off
 * Scene.soundEffects. The rendered video, if any, is read from
 * RenderJobManager's real job list (read-only — no job is submitted from
 * here). Nothing is generated by this panel.
 */
export function AssetInspectorPanel({ assets }: AssetInspectorPanelProps) {
  const { characterReferenceImages, environmentReferenceImages, videoUrl, musicCue, voiceAssignments, soundEffects } = assets;

  return (
    <div className="space-y-4 text-xs">
      <Section title="Images" icon={<ImageIcon className="h-3 w-3" />}>
        {characterReferenceImages.length === 0 && environmentReferenceImages.length === 0 ? (
          <p className="text-zinc-500">No reference images generated for this scene's characters or location yet.</p>
        ) : (
          <div className="grid grid-cols-3 gap-2 sm:grid-cols-5">
            {[
              ...characterReferenceImages.map((image) => ({ url: image.url, label: image.characterName })),
              ...environmentReferenceImages.map((image) => ({ url: image.url, label: "Location reference" })),
            ].map((image, i) => (
              <div key={i} className="overflow-hidden rounded-lg border border-white/10 bg-white/[0.02]">
                {image.url ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={image.url} alt={image.label} className="aspect-square w-full object-cover" />
                ) : (
                  <div className="flex aspect-square w-full items-center justify-center">
                    <ImageIcon className="h-5 w-5 text-white/25" />
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </Section>

      <Section title="Video Assets" icon={<Film className="h-3 w-3" />}>
        {videoUrl ? (
          <a href={videoUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-brand-300 hover:underline">
            <Play className="h-3.5 w-3.5" /> Open rendered video
          </a>
        ) : (
          <p className="text-zinc-500">Not rendered yet.</p>
        )}
      </Section>

      <Section title="Music" icon={<Music2 className="h-3 w-3" />}>
        {musicCue ? (
          <p className="text-zinc-300">
            {musicCue.cue.moodTags?.join(", ") ?? musicCue.cue.style ?? "Music cue"}
            <span className="ml-1.5 text-zinc-500">({musicCue.source === "EXISTING" ? "director-authored" : "derived"})</span>
          </p>
        ) : (
          <p className="text-zinc-500">No music cue planned for this scene.</p>
        )}
      </Section>

      <Section title="Voices" icon={<Volume2 className="h-3 w-3" />}>
        {voiceAssignments.length === 0 ? (
          <p className="text-zinc-500">No characters to voice in this scene.</p>
        ) : (
          <ul className="space-y-1">
            {voiceAssignments.map((assignment, i) => (
              <li key={i} className="flex items-center justify-between border-b border-white/5 py-1">
                <span className="text-zinc-400">{assignment.characterName}</span>
                <span className="text-zinc-300">{assignment.voiceName ?? "—"}</span>
              </li>
            ))}
          </ul>
        )}
      </Section>

      <Section title="Effects" icon={<Waves className="h-3 w-3" />}>
        {soundEffects.length === 0 ? (
          <p className="text-zinc-500">No sound effects planned for this scene.</p>
        ) : (
          <ul className="space-y-1">
            {soundEffects.map((effect, i) => (
              <li key={i} className="text-zinc-300">
                {effect.name}
                {effect.timestampSeconds !== undefined && <span className="ml-1.5 text-zinc-500">@ {effect.timestampSeconds}s</span>}
              </li>
            ))}
          </ul>
        )}
      </Section>
    </div>
  );
}

function Section({ title, icon, children }: { title: string; icon?: React.ReactNode; children: React.ReactNode }) {
  return (
    <div>
      <p className="mb-1.5 inline-flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-zinc-500">
        {icon}
        {title}
      </p>
      {children}
    </div>
  );
}

export default AssetInspectorPanel;
